name: Fetch NIH dementia grants

on:
  schedule:
    - cron: "0 6 * * *"   # run daily at 06:00 UTC
  workflow_dispatch:       # allow manual trigger

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Fetch NIH data
        run: |
          mkdir -p data
          KEYWORDS='dementia OR dementias OR "Alzheimer disease" OR "Alzheimer'\''s disease" OR Alzheimer* OR Alzeimer* OR ADRD OR "Alzheimer’s disease and related dementias" OR AD/ADRD OR "Lewy body dementia" OR "dementia with Lewy bodies" OR LBD OR DLB OR "Parkinson'\''s disease dementia" OR PDD OR "frontotemporal dementia" OR "frontotemporal lobar degeneration" OR FTD OR FTLD OR "behavioral variant frontotemporal dementia" OR bvFTD OR "primary progressive aphasia" OR PPA OR "semantic variant PPA" OR svPPA OR "nonfluent variant PPA" OR nfvPPA OR "logopenic variant PPA" OR lvPPA OR "corticobasal degeneration" OR CBD OR "progressive supranuclear palsy" OR PSP OR "posterior cortical atrophy" OR PCA OR "vascular dementia" OR VaD OR "vascular cognitive impairment" OR VCID OR "mixed dementia" OR "multiple-etiology dementia" OR MED OR "mild cognitive impairment" OR MCI OR "early-onset dementia" OR "young-onset dementia" OR "familial Alzheimer*" OR "early-onset Alzheimer*" OR EOAD OR "Down syndrome Alzheimer*" OR "DS-AD" OR "neurodegenerative dementia"'

          API='https://api.reporter.nih.gov/v2/projects/search'
          OFFSET=0
          LIMIT=500

          echo '{"results":[],"meta":{}}' > data/latest.json


          while true; do
            PAYLOAD=$(cat <<JSON
            
{
  "criteria":{
    "fiscal_years": [2024, 2025],
    "include_active_projects": true,
    "advanced_text_search": {
      "operator": "or",
      "search_field": "all",
      "search_text": "$KEYWORDS"
                            }
             },
  "include_fields": [
    "ProjectNum",
    "ProjectTitle",
    "AbstractText",
    "OrgName",
    "OrgCountry",
    "Agency",
    "ICName",
    "AwardAmount",
    "FiscalYear"
  ],
  "offset": $OFFSET,
  "limit": $LIMIT,
  "sort_field": "FiscalYear",
  "sort_order": "desc"
}

JSON
)


            RESP=$(curl -s -X POST "$API" \
              -H "Content-Type: application/json " \
              --data "$PAYLOAD")

            COUNT=$(echo "$RESP" | jq '.results | length')
            TOTAL=$(echo "$RESP" | jq '.meta.total // 0')

            jq --argjson page "$RESP" \
               '.results += ($page.results // []) | .meta = $page.meta' \
               data/latest.json > data/latest.tmp && mv data/latest.tmp data/latest.json

            if [ "$COUNT" -eq 0 ]; then
              break
            fi

            OFFSET=$((OFFSET + LIMIT))
            if [ "$OFFSET" -ge "$TOTAL" ]; then
              break
            fi
          done

      - name: Commit JSON
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add data/latest.json
          git commit -m "Update NIH dementia grants data" || echo "No changes to commit"
          git push
