      - name: Fetch NIH data
        run: |
          mkdir -p data
          API='https://api.reporter.nih.gov/v2/projects/search'
          OFFSET=0
          LIMIT=500

          echo '{"results":[],"meta":{}}' > data/latest.json

          while true; do
            jq ".offset=$OFFSET | .limit=$LIMIT" payload.json > query.json

            # Fetch one page
            curl -s -X POST "$API" \
              -H "Content-Type: application/json" \
              --data @query.json > page.json

            COUNT=$(jq '.results | length' page.json)
            TOTAL=$(jq '.meta.total // 0' page.json)

            # Merge into master file
            jq -s '
              {
                results: (.[0].results + .[1].results),
                meta: .[1].meta
              }
            ' data/latest.json page.json > data/latest.tmp && mv data/latest.tmp data/latest.json

            echo "Fetched $COUNT records (offset $OFFSET / total $TOTAL)"

            # Stop if no more results
            if [ "$COUNT" -eq 0 ]; then
              break
            fi

            OFFSET=$((OFFSET + LIMIT))
            if [ "$OFFSET" -ge "$TOTAL" ]; then
              break
            fi

            # ⏱️ Sleep to avoid hammering the API
            sleep 2
          done
